name: toly
description: toly cmd tools.
version: 0.0.3
repository: https://github.com/toly1994328/toly

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  archive: ^3.4.10 # 解压
  yaml: ^3.1.2
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

executables:
  toly:
